name: Build and test
on: [push, pull_request]
permissions:
  contents: read
jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          targets: x86_64-pc-windows-msvc
      - run: cargo fmt --check
      - run: cargo clippy --locked --all-targets -- -D warnings
      - name: Test
        shell: pwsh
        run: ./scripts/test.ps1
      - run: cargo build --locked --release
      - shell: pwsh
        run: ./scripts/package.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: EFTRegionWatcher-win-x64
          path: target/dist/*
